spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/seoul
    driver-class-name: org.h2.Driver
    username: insik
    password: 
  sql:
    init:
      mode: always
      schema-locations: classpath:bcsd.sql
    